version: '3'

services:
  jupyter:
    command: "jupyter-lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    stdin_open: true
    tty: true
    build:
        context: .
        dockerfile: Dockerfile_Jupyter
    container_name: jupyter-server
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/miaw
    environment:
      - JUPYTER_ENABLE_LAB=yes  # Habilita Jupyter Lab
      - JUPYTER_TOKEN=miawmiaw  # Cambia esto a tu token deseado
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    
